### ISSUE TITLE
PostgresProxy Class Bleah's on M:M relationship

### ISSUE THREAD

**Issue by kbower** [kbower/tickettest1#445]
_Imported from trac ticket 445.
Created by **rneville**
Opened in trac: Nov 6, 2010, 7:52:26 AM
Last modified in trac: Nov 6, 2010, 7:21:04 PM_
***
_by rneville:_
Test scenario:
 * Go to paster shell
 * Create three trucks:
```
t1 = Truck()
t1.truckid = u'TRK01'
t2 = Truck()
t2.truckid = u'TRK02'
t3 = Truck()
t3.truckid = u'TRK03'
DBSession.add(t1)
DBSession.add(t2)
DBSession.add(t3)

tg1 = TruckGroup()
tg1.truckgroupid = u'TG1'
DBSession.add(tg1)

DBSession.flush()
transaction.commit()
```Now quit() out of paster shell and restart it again and try to associate the trucks you just created to the truck group you just created....
```
tg = DBSession.query(TruckGroup).all()[0]
tg.trucks.extend(DBSession.query(Truck).all())
DBSession.flush()
```
At this point you will get the following "bleah":
```
>>> DBSession.flush()
03:24:12,410 INFO  [sqlalchemy.engine.base.Engine.0x...3910] ROLLBACK
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/scoping.py", line 132, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1367, in flush
    self._flush(objects)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/session.py", line 1448, in _flush
    flush_context.execute()
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 299, in execute
    rec.execute(self)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/unitofwork.py", line 401, in execute
    self.dependency_processor.process_saves(uow, states)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/dependency.py", line 1021, in process_saves
    secondary_update, secondary_delete)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/orm/dependency.py", line 1064, in _run_crud
    connection.execute(statement, secondary_insert)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1881, in execute
    object, *multiparams, **params)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/interfaces.py", line 149, in execute
    return execute(clauseelement, *multiparams, **params)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1191, in execute
    params)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1271, in _execute_clauseelement
    return self.__execute_context(context)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1297, in __execute_context
    context.parameters, context=context)
  File "/home/rarch/tg2env/lib/python2.6/site-packages/SQLAlchemy-0.6.4.2kbdev-py2.6-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1899, in _cursor_executemany
    cursor, statement, parameters, context, True)
  File "/home/rarch/trunk/src/appserver/pylotengine/config/middleware.py", line 25, in cursor_execute
    for param, value in parameters.items():
AttributeError: 'tuple' object has no attribute 'items'
```
It's pointing to PostgresProxy in source:trunk/src/appserver/pylotengine/config/middleware.py#L25

**Comment by kbower** [comment]
_**kbower** trac comment on Nov 6, 2010, 8:57:22 AM:_

Comment out for now. 
Not blocker while only running oracle.

**Comment by kbower** [comment]
_**rneville** trac comment on Nov 6, 2010, 12:33:33 PM:_

(In [[891]](../commit/5f70a794b7509fa1c7ffa7a72cb0569a600d5b16))
addresses #349 and changes the vendor for mockdata's MODERNSCROLL because only RN could make something that awesome ;)


also adds dynaforms for truck, truck groups

addresses #445 too though just a bandaid for now, will need to be fixed for real at some point

**Comment by kbower** [comment]
_**kbower** trac comment on Nov 6, 2010, 3:07:56 PM:_

Problem introduced in #430

**Comment by kbower** [comment]
_**kbower** trac comment on Nov 6, 2010, 3:13:41 PM:_

see http://groups.google.com/group/sqlalchemy/browse_thread/thread/57badf7c5c177850?hl=en

**Comment by kbower** [comment]
_**kbower** trac comment on Nov 6, 2010, 7:21:04 PM:_

(In [[894]](../commit/975f89fa318b619ed08c6b313ba128d419b6b7a5))
 Fix problem with crash when postgres proxy had an executemany.  Fixes #445

**Comment by kbower** [comment]
_**kbower** trac status change on Nov 6, 2010, 7:21:04 PM:_ **closed**
